server: 
  port: 8081
  servlet: 
    context-path: /sso-resource-server

logging: 
  level: 
    org.springframework: DEBUG
    #org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE
    
####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://gkovan.verify.ibm.com/oidc/endpoint/default
          jwk-set-uri: https://gkovan.verify.ibm.com/v1.0/endpoint/default/jwks